project:
  type: website
  output-dir: docs
  render: 
    - "Cleaning*.qmd"
    - "*.qmd"
    - "!Map*.qmd"

website:
  title: "tea-teachers"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: CleaningTEASalaries.qmd
        text: "Cleaning TEA Salaries"
      - href: CleaningEnrollment.qmd
        text: "Cleaning TEA Enrollment"
      - href: CleaningCPI-ALICE.qmd
        text: "Cleaning CPI and ALICE"
      - href: AnalysisInitial.qmd
        text: "Initial Analysis"
      - href: AnalysisNCES.qmd
        text: "NCES District Type Analysis"
      - href: AnalysisSecondary.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap



