project:
  type: website
  output-dir: docs
  render: 
    - "Cleaning*.qmd"
    - "*.qmd"

website:
  title: "tea-teachers"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: CleaningTEASalaries.qmd
        text: "Cleaning TEA Salaries"
      - href: CleaningEnrollment.qmd
        text: "Cleaning TEA Enrollment"
      - href: CleaningCPI-ALICE.qmd
        text: "Cleaning CPI and ALICE"
      - href: AnalysisInitial.qmd
        text: "Initial Analysis"
      - href: Map1.qmd
        text: "TEA District Types Map"
      - href: Map2.qmd
        text: "Bill Categories Map"
      - href: Map3.qmd
        text: "Difference in Salary and Cost of Living Map"
      - href: AnalysisRegion20.qmd
        text: "Region 20 Analysis"
      - href: AnalysisNCES.qmd
        text: "NCES District Type Analysis"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

    code-overflow: wrap



