project:
  type: website


website:
  title: "tea-teachers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CleaningTEASalaries.qmd
        text: "Cleaning TEA Salaries"
      - href: CleaningEnrollment.qmd
        text: "Cleaning TEA Enrollment"
      - href: CleaningCPI-ALICE.qmd
        text: "Cleaning CPI and ALICE"
      - href: Analysis.qmd
        text: Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



